POST http://localhost:3008/api/produtos
Content-Type: application/json

{
  "nome": "PRODUCT TEST",
  "preco": 49.90
}


###

GET http://localhost:3008/api/produtos

###

GET http://localhost:3008/api/produtos/676488917e385aba2cb82db1

###

DELETE http://localhost:3008/api/produtos/676488897e385aba2cb82dad


###

PUT http://localhost:3008/api/produtos/676488917e385aba2cb82db1
Content-Type: application/json

{
  "nome": "BLUSA CODIGO ROSITA",
  "preco": 29
}
###CRIAR NOVO VENDEDOR

POST  http://localhost:3008/api/vendedor
Content-Type: application/json

{
  "nome": "dauran AGUIAR lima",
  "endereco": "Rua JORGE LARCIDIS",
  "telefone": "45988328490",
  "documento": "068.371.269-12",
  "cidade": "CASVELLIS-RN",
  "saldo": 99
}


###

GET http://localhost:3008/api/vendedor

###

GET http://localhost:3008/api/vendedor/67709f24210cda5564745d2c

###

DELETE http://localhost:3008/api/vendedor/6774576d6daea097548120b8


### Criar novo pedido
POST http://localhost:3008/api/pedido
Content-Type: application/json


{
  "produtos": [
    {
      "produto": "676488c57e385aba2cb82dc5",
      "quantidade": 9
    }
  ],
  "vendedor": "676d8a2dcd7ffe69d834045d",
  "status": "Aberto"
}



###Buscar todos os pedidos
GET http://localhost:3008/api/pedido

### Buscar pedido por ID
GET http://localhost:3008/api/pedido/6774c26d5756f833a483646b

### Atualizar pedido
PUT http://localhost:3008/api/pedido/6774c26d5756f833a483646b
Content-Type: application/json

{ 
  "vendedor": { 
    "nome": "DAURITIZIS LIMA",
    "cidade": "CASCAMEL"
  },  
  "produtos": [{
    "nome": "CAMISETA BASICA GOLA V",
    "quantity": 2,
    "preco": 298
  }],
  "data": "2022-03-14T15:27:50.408Z",
  "totalValor": 298
}
### Deletar pedido
DELETE http://localhost:3008/api/pedido/677435fb360fd79b5ed1ab40




###
  POST http://localhost:3008/api/acerto
  Content-Type: application/json

  {
    "pedidoId": "7435fb360fd79b",
    "produtos": [{
      "nome": "teste prod1",
      "quantity": 2,
      "devolvido": 2,
      "preco": 10
    }],
    "vendedor": { 
      "nome": "DAURAN LIMA",
      "cidade": "CASCAVEL"
    },
    "dataAcerto": "2025-01-08",
    "totalValor": 1024,
    "totalVendido": 200,
    "descontos": 50,
    "saldoAtual": 0,
    "recebido": 100,
    "totalAcerto": 100,
    "novoSaldoVendedor": 50
  }